server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql:///test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://39.108.188.42:2181
  protocol:
    port: -1

  consumer:
    check: false
    timeout: 10000
    retries: 3